#!/usr/bin/env python3
"""agents_sync.py - one org chart, two faces, zero drift.

The problem it exists for: the OS holds every digital employee in one registry
(roles/employees.yaml - the job, the charter, the prohibitions), but Claude Code
addresses agents through .claude/agents/<name>.md files. Keep those two by hand
and they drift: the charter narrows, the agent file keeps the old grant, and the
boundary you wrote stops being the boundary that runs. The 2026 fix for every
seam like this in the OS has been the same: one source, a generator, and a
checker that fails loud.

This makes the registry the single source. Each non-retired row generates one
agent file, so the user can talk TO a seat by name ("ask the assistant what is
waiting"), dispatch it as a subagent, and give it standing instructions by
editing the row - not by editing a second file that quietly disagrees with the
first. Fire the seat (retire the row), and the agent file goes with it.

What a generated agent file carries, because a team member without a charter is
just a prompt: the job in plain language, the measure, the read-list, what it
may write, what it must never do, the honest status, and the closing act -
recording its own run to brain/agent-runs.jsonl so the org chart shows what
actually ran.

Subcommands, standard library only, ASCII-safe output:

  check   Report drift between the registry and .claude/agents/. Exit 1 on any
          drift, including a hand-written file shadowing a rostered seat
          ([foreign]) and a generated file edited after generation ([modified]).
  apply   Write the agent files, then re-check. Only ever creates, updates, or
          removes a file that carries this script's marker AND still matches
          the digest the marker records - a hand-written file, or a generated
          one you edited, is named and left alone (edits are never clobbered).

Invariants: the registry is never written by this script (changes go through
the three registry doors: hire, review diff, retirement). Generated files carry
a sentinel and are the only files touched. Standard library only, no network,
no API key. `python scripts/employee_verdict.py drift` remains the cross-check:
it names any agent file with no registry row behind it.

Usage:
  python scripts/agents_sync.py check
  python scripts/agents_sync.py apply
  python scripts/agents_sync.py check --json
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTRY = REPO_ROOT / "roles" / "employees.yaml"
AGENTS_DIR = REPO_ROOT / ".claude" / "agents"

# One line, first line of the body, and the whole ownership contract: a file
# without this marker is not ours and is never touched. The marker also carries
# a digest of the generated body, so "carries the marker" and "is still what we
# generated" are separate questions - a file the operator edited below the
# marker is reported as [modified] and never overwritten or deleted.
SENTINEL_PREFIX = ("<!-- generated by scripts/agents_sync.py from roles/employees.yaml - "
                   "do not edit; edit the registry row and re-run apply")
SENTINEL = SENTINEL_PREFIX + " -->"  # legacy form, pre-digest; still recognised
_HASH_RE = re.compile(r"body-sha256:([0-9a-f]{64})")

# A seat id becomes a filename under .claude/agents/. Anything else - path
# separators, dots, uppercase - is rejected at load time, because an id like
# ../../README would otherwise resolve OUTSIDE the agents dir and overwrite a
# repository file while reporting success.
ID_RE = re.compile(r"^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$")


def _strip_sentinel(text: str) -> str:
    return "\n".join(l for l in text.split("\n")
                     if not l.startswith(SENTINEL_PREFIX))


def _body_digest(text: str) -> str:
    return hashlib.sha256(_strip_sentinel(text).encode("utf-8")).hexdigest()


def _recorded_digest(text: str) -> str | None:
    for line in text.split("\n"):
        if line.startswith(SENTINEL_PREFIX):
            m = _HASH_RE.search(line)
            return m.group(1) if m else None
    return None


def _flat_yaml():
    """Load scripts/flat_yaml.py by explicit path rather than by import name, so
    this works the same whether or not scripts/ is on sys.path."""
    src = Path(__file__).resolve().parent / "flat_yaml.py"
    spec = importlib.util.spec_from_file_location("founderos_flat_yaml", src)
    if spec is None or spec.loader is None:  # pragma: no cover - packaging accident
        raise SystemExit("agents_sync: cannot load scripts/flat_yaml.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def load_registry(path: Path) -> list[dict]:
    if not path.exists():
        raise SystemExit(
            f"agents_sync: no registry at {path}. The org chart is the single "
            f"source for agent files; copy templates/roles/employees.yaml first.")
    try:
        rows = _flat_yaml().parse_flat_yaml(
            path.read_text(encoding="utf-8"), filename=str(path),
            record_key="employees")
    except ValueError as e:
        raise SystemExit(f"agents_sync: {e}") from None
    seen: set[str] = set()
    for i, r in enumerate(rows, 1):
        eid = r.get("id") or ""
        if not eid:
            raise SystemExit(f"agents_sync: registry entry #{i} has no id")
        if not ID_RE.match(eid):
            raise SystemExit(
                f"agents_sync: registry entry #{i} has invalid id '{eid}'. Ids are "
                f"lowercase letters, digits, and inner hyphens (max 64 chars) - they "
                f"become filenames under .claude/agents/ and nothing else is safe there.")
        if eid in seen:
            raise SystemExit(
                f"agents_sync: duplicate id '{eid}' (entry #{i}). Two rows with one id "
                f"would silently overwrite each other's agent file; merge or rename.")
        seen.add(eid)
    return rows


def _first_sentence(text: str, cap: int = 180) -> str:
    text = (text or "").strip()
    dot = text.find(". ")
    out = text[: dot + 1] if 0 < dot < cap else text[:cap]
    return out.strip()


def render_agent(row: dict) -> str:
    """One agent file from one registry row. Everything here is READ from the
    row - nothing is invented, because this file is the seat's standing
    instruction sheet and an invented line would be a permission nobody granted."""
    eid = row.get("id", "")
    title = (row.get("job_title") or eid).strip()
    desc = _first_sentence(row.get("job_description", ""))
    tools = (row.get("tools") or "").strip()
    head = [
        "---",
        f"name: {eid}",
        f"description: {title}. {desc}".rstrip(),
        f"tools: {tools}" if tools else "tools:",
        "---",
    ]
    body = [
        "",
        f"# {title}",
        "",
        f"You are the `{eid}` seat on this operator's org chart "
        f"(roles/employees.yaml). The row that generated this file IS your "
        f"contract: the operator manages you by editing it, and your job is to "
        f"stay inside it even when a wider action looks helpful.",
        "",
        "## The job",
        "",
        (row.get("job_description") or "").strip(),
        "",
        f"**The measure you are judged by:** {(row.get('kpi') or 'not set').strip()}",
        f"**Status:** {(row.get('status') or 'gated').strip()} - if gated, you run "
        f"only when the operator dispatches you, and your first real run is what "
        f"earns active.",
        "",
        "## Read these first",
        "",
        f"{(row.get('inputs') or 'nothing named - ask before reading widely').strip()}",
        "",
        "Also read `core/working-preferences.md` if it exists - its Active rows "
        "are how this operator wants to be worked with, and they gate your "
        "output the same way they gate every other surface.",
        "",
        "## What you may write",
        "",
        f"{(row.get('may_write') or 'nothing - this is a propose-only seat').strip()}",
        "",
        "## Never",
        "",
        f"{(row.get('never') or 'act outside the row above').strip()}",
        "",
        "The `never` field above is controlling. If it names no connector, "
        "nothing leaves this machine by your hand: no send, no post, no external "
        "call - drafts stop at files, and delivery belongs to the operator. If "
        "it explicitly names a connector, use only that connector, only for the "
        "action the row names, and only under the row's consent rule.",
        "",
        "## Your closing act (every run)",
        "",
        "Record the run so it leaves a trace whether or not anyone was watching:",
        "",
        "```",
        f"python scripts/agent_runs.py record --seat {eid} "
        f"--trigger \"<what set this run off>\" "
        f"--read \"<files actually read>\" "
        f"--produced \"<files or item ids written>\" --outcome ok",
        "```",
        "",
        "Use `--outcome refused --could-not \"<why>\"` when the charter said no, "
        "and `--outcome failed --could-not \"<why>\"` when it broke - the script "
        "requires the reason for both. A refusal is the charter working, not a "
        "failure. Skip silently if the script is absent.",
        "",
    ]
    digest = hashlib.sha256("\n".join(head + body).encode("utf-8")).hexdigest()
    sentinel = f"{SENTINEL_PREFIX} | body-sha256:{digest} -->"
    return "\n".join(head + [sentinel] + body)


def is_generated(path: Path) -> bool:
    try:
        return SENTINEL_PREFIX in path.read_text(encoding="utf-8")
    except OSError:
        return False


def _classify_owned(text: str, wanted_text: str | None) -> str:
    """For a file carrying the marker: is it still OURS to touch?

    Returns one of:
      clean    - matches its row's render exactly
      stale    - untouched generated content that no longer matches the row
      orphan   - untouched generated content whose row is retired or gone
      modified - the operator (or anyone) edited below the marker; NEVER touched
    """
    recorded = _recorded_digest(text)
    if recorded is not None:
        if recorded != _body_digest(text):
            return "modified"
        if wanted_text is None:
            return "orphan"
        return "clean" if text == wanted_text else "stale"
    # Legacy marker with no digest: owned only when the content (minus the
    # marker line) exactly matches the current render - then apply may rewrite
    # it to the digest form. Anything else could carry the operator's edits,
    # and a guess here destroys their work, so it is treated as modified.
    if wanted_text is not None and _strip_sentinel(text) == _strip_sentinel(wanted_text):
        return "stale"
    return "modified"


def compute(registry: Path, agents_dir: Path) -> dict:
    """The full drift picture, computed once and shared by check and apply."""
    rows = load_registry(registry)
    wanted = {r["id"]: render_agent(r) for r in rows
              if (r.get("status") or "") != "retired"}
    existing = {p.stem: p for p in sorted(agents_dir.glob("*.md"))} \
        if agents_dir.is_dir() else {}

    missing = [i for i in wanted if i not in existing]
    stale, foreign, orphan, modified = [], [], [], []
    for stem, p in existing.items():
        text = p.read_text(encoding="utf-8") if p.is_file() else ""
        mine = SENTINEL_PREFIX in text
        if stem in wanted:
            if not mine:
                foreign.append(stem)  # a hand-written file shadows the row - never touched
                continue
            kind = _classify_owned(text, wanted[stem])
            if kind == "stale":
                stale.append(stem)
            elif kind == "modified":
                modified.append(stem)
        elif mine:
            kind = _classify_owned(text, None)
            if kind == "orphan":
                orphan.append(stem)  # row retired or deleted; verified ours - may go
            else:
                modified.append(stem)  # edited or unverifiable - never deleted
        # not mine and not in wanted: someone else's agent - drift's job to name
    return {"wanted": wanted, "existing": existing, "missing": missing,
            "stale": stale, "foreign": foreign, "orphan": orphan,
            "modified": modified}


def _safe_target(agents_dir: Path, stem: str) -> Path:
    """The one place a stem becomes a path. Refuses anything that would land
    outside the agents dir - the load-time id check should make this
    unreachable, but a write outside the boundary is the failure worth a
    second, mechanical lock."""
    target = (agents_dir / f"{stem}.md").resolve()
    if not target.is_relative_to(agents_dir.resolve()):
        raise SystemExit(f"agents_sync: refusing to touch {target} - outside "
                         f"{agents_dir}. A seat id must stay a bare filename.")
    return target


def cmd_check(args) -> int:
    state = compute(Path(args.registry), Path(args.agents_dir))
    drift = {k: state[k] for k in ("missing", "stale", "orphan", "foreign", "modified")}
    clean = not any(drift.values())
    if args.json:
        print(json.dumps({"clean": clean, **{k: sorted(v) for k, v in drift.items()}},
                         ensure_ascii=True))
        return 0 if clean else 1
    for i in state["missing"]:
        print(f"[missing] {i}: registry row has no agent file - run apply")
    for i in state["stale"]:
        print(f"[stale] {i}: agent file no longer matches its registry row - run apply")
    for i in state["orphan"]:
        print(f"[orphan] {i}: generated agent file with no live registry row - "
              f"apply removes it")
    for i in state["foreign"]:
        print(f"[foreign] {i}: hand-written agent file shadows a registry row - "
              f"left alone; fold it into the row or rename it")
    for i in state["modified"]:
        print(f"[modified] {i}: generated agent file was edited after generation - "
              f"left alone; fold the edit into the registry row, or delete the "
              f"file yourself and run apply")
    if clean:
        print(f"agents_sync: {len(state['wanted'])} seat(s), agent files match the "
              f"registry.")
        return 0
    return 1


def cmd_apply(args) -> int:
    agents_dir = Path(args.agents_dir)
    state = compute(Path(args.registry), agents_dir)
    agents_dir.mkdir(parents=True, exist_ok=True)
    written, removed = [], []
    for i in state["missing"] + state["stale"]:
        _safe_target(agents_dir, i).write_text(state["wanted"][i],
                                               encoding="utf-8", newline="\n")
        written.append(i)
    for i in state["orphan"]:
        _safe_target(agents_dir, i).unlink()
        removed.append(i)
    for i in state["foreign"]:
        print(f"[foreign] {i}: hand-written file left alone")
    for i in state["modified"]:
        print(f"[modified] {i}: edited after generation - left alone; fold the "
              f"edit into the registry row, or delete the file and re-run apply")
    print(f"agents_sync: wrote {len(written)}, removed {len(removed)}, "
          f"{len(state['wanted'])} seat(s) total.")
    return 1 if state["modified"] else 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Generate .claude/agents/ from roles/employees.yaml. One source.")
    sub = p.add_subparsers(dest="cmd", required=True)
    for name, fn, help_text in (
            ("check", cmd_check, "Report drift between registry and agent files."),
            ("apply", cmd_apply, "Write agent files from the registry, remove orphans.")):
        sp = sub.add_parser(name, help=help_text)
        sp.add_argument("--registry", default=str(REGISTRY))
        sp.add_argument("--agents-dir", dest="agents_dir", default=str(AGENTS_DIR))
        if name == "check":
            sp.add_argument("--json", action="store_true")
        sp.set_defaults(func=fn)
    args = p.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
