#!/usr/bin/env python3
"""agents_sync.py - one org chart, two faces, zero drift.

The problem it exists for: the OS holds every digital employee in one registry
(roles/employees.yaml - the job, the charter, the prohibitions), but Claude Code
addresses agents through .claude/agents/<name>.md files. Keep those two by hand
and they drift: the charter narrows, the agent file keeps the old grant, and the
boundary you wrote stops being the boundary that runs. The 2026 fix for every
seam like this in the OS has been the same: one source, a generator, and a
checker that fails loud.

This makes the registry the single source. Each non-retired row generates one
agent file, so the user can talk TO a seat by name ("ask the assistant what is
waiting"), dispatch it as a subagent, and give it standing instructions by
editing the row - not by editing a second file that quietly disagrees with the
first. Fire the seat (retire the row), and the agent file goes with it.

What a generated agent file carries, because a team member without a charter is
just a prompt: the job in plain language, the measure, the read-list, what it
may write, what it must never do, the honest status, and the closing act -
recording its own run to brain/agent-runs.jsonl so the org chart shows what
actually ran.

The read-list also grows. A note in brain/knowledge/ may carry an optional
`seats:` line, and every seat it names gets a POINTER to that note folded into
its read-list - id, topic, path, never the body. That is the second loop that
makes "it grows with you" true: the first is core/working-preferences.md, read
before output. Nothing auto-tags; a tag is always the operator's yes, and a
declined note is recorded as `seats: none` so it is never raised again.

Subcommands, standard library only, ASCII-safe output:

  check   Report drift between the registry and .claude/agents/. Exit 1 on any
          drift, including a hand-written file shadowing a rostered seat
          ([foreign]) and a generated file edited after generation ([modified]).
  apply   Write the agent files, then re-check. Only ever creates, updates, or
          removes a file that carries this script's marker AND still matches
          the digest the marker records - a hand-written file, or a generated
          one you edited, is named and left alone (edits are never clobbered).

Invariants: the registry is never written by this script (changes go through
the three registry doors: hire, review diff, retirement). Generated files carry
a sentinel and are the only files touched. Standard library only, no network,
no API key. `python scripts/employee_verdict.py drift` remains the cross-check:
it names any agent file with no registry row behind it.

Usage:
  python scripts/agents_sync.py check
  python scripts/agents_sync.py apply
  python scripts/agents_sync.py check --json
  python scripts/agents_sync.py check --knowledge-dir <dir>   (read-only, testing)
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTRY = REPO_ROOT / "roles" / "employees.yaml"
AGENTS_DIR = REPO_ROOT / ".claude" / "agents"

# One line, first line of the body, and the whole ownership contract: a file
# without this marker is not ours and is never touched. The marker also carries
# a digest of the generated body, so "carries the marker" and "is still what we
# generated" are separate questions - a file the operator edited below the
# marker is reported as [modified] and never overwritten or deleted.
SENTINEL_PREFIX = ("<!-- generated by scripts/agents_sync.py from roles/employees.yaml - "
                   "do not edit; edit the registry row and re-run apply")
SENTINEL = SENTINEL_PREFIX + " -->"  # legacy form, pre-digest; still recognised
_HASH_RE = re.compile(r"body-sha256:([0-9a-f]{64})")

# A seat id becomes a filename under .claude/agents/. Anything else - path
# separators, dots, uppercase - is rejected at load time, because an id like
# ../../README would otherwise resolve OUTSIDE the agents dir and overwrite a
# repository file while reporting success.
ID_RE = re.compile(r"^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$")

# The knowledge fold. A seat is as ignorant on run 50 as on run 1 unless what
# the operator has learned reaches its read-list. Any brain/knowledge note may
# carry an optional `seats:` line, and this folds a POINTER to that note into
# the read-list of every seat it names - id, topic, path, never a sentence of
# the body. brain/knowledge/README.md's standing rule is "do not hard-parse
# note bodies", and the seat opens the file itself when it runs.
#
# Three states, and the third is the one that matters:
#   absent        never reviewed - a candidate for the morning-loop sweep
#   seats: <ids>  routed to those seats
#   seats: none   reviewed and deliberately routed to nobody - the tombstone.
#                 Without it a declined note comes back every morning, which is
#                 the zombie ask this OS already has a risk-register row for.
#
# This adds NO ownership logic and is not allowed to. The fold happens inside
# render_agent, so the body digest in the marker already covers it: a new tag
# makes the seat [stale], apply converges, and a file the operator edited stays
# [modified] and is never clobbered. An install with no tagged notes renders
# byte-identical agent files to a pre-fold install.
KNOWLEDGE_DIR = REPO_ROOT / "brain" / "knowledge"
KNOWLEDGE_CAP = 20  # a heavily-tagged seat must not bloat its own instruction sheet
# A pointer is a label, so the fields that become one are bounded. Notes are
# often written from an outside source - a book, an article, a page someone
# scraped - so a topic line is not always text the operator composed, and an
# unbounded one turns the pointer back into the body this whole design refuses
# to copy. Bounding is not sanitising and is not claimed to be: it keeps a
# label a label, and the block below still tells the seat these are pointers.
KNOWLEDGE_ID_CAP = 64
KNOWLEDGE_TOPIC_CAP = 120
_FRONTMATTER_RE = re.compile(r"^---\r?\n(.*?)\r?\n---", re.S)


def _fm_field(fm: str, key: str, cap: int | None = None) -> str:
    m = re.search(rf"^{key}:\s*(.+)$", fm, re.M)
    if not m:
        return ""
    val = " ".join(m.group(1).split()).strip("\"'")
    if cap is not None and len(val) > cap:
        val = val[:cap].rstrip() + "..."
    return val


def _scan_knowledge(knowledge_dir: Path | None) -> list[dict]:
    """Every knowledge note's frontmatter, parsed once. A missing directory is
    not an error: an install with no knowledge layer yet is a valid install and
    must render exactly the agent files it renders today."""
    if knowledge_dir is None or not Path(knowledge_dir).is_dir():
        return []
    notes: list[dict] = []
    for path in sorted(Path(knowledge_dir).glob("*.md")):
        if path.name.lower() == "readme.md":
            continue  # the index, not a note
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        m = _FRONTMATTER_RE.match(text)
        if not m:
            continue
        fm = m.group(1)
        raw = _fm_field(fm, "seats")
        if not raw:
            continue  # no field at all - never reviewed, routed nowhere
        seats = [s.strip() for s in raw.strip("[]").split(",") if s.strip()]
        if [s.lower() for s in seats] == ["none"]:
            seats = []  # the tombstone: reviewed, deliberately routed to nobody
        notes.append({
            "file": path.name,
            "id": _fm_field(fm, "id", KNOWLEDGE_ID_CAP) or path.stem[:KNOWLEDGE_ID_CAP],
            "topic": _fm_field(fm, "topic", KNOWLEDGE_TOPIC_CAP)
                     or path.stem[:KNOWLEDGE_TOPIC_CAP],
            "captured": _fm_field(fm, "captured"),
            "seats": seats,
        })
    return notes


def _seat_knowledge(eid: str, knowledge_dir: Path | None,
                    notes: list[dict] | None = None) -> list[dict]:
    """The notes routed to one seat, most recently captured first. Ties break on
    id so two notes captured the same day never reorder between runs - an
    unstable order would show as permanent false drift.

    Pass `notes` to reuse one scan across every seat; compute() does, so a
    mature install with hundreds of notes is read once per run rather than once
    per seat."""
    if notes is None:
        notes = _scan_knowledge(knowledge_dir)
    mine = [n for n in notes if eid in n["seats"]]
    return sorted(mine, key=lambda n: (n["captured"], n["id"]), reverse=True)


def _knowledge_block(notes: list[dict]) -> list[str]:
    """The read-list's growing half. No notes, no block - that is what keeps an
    untagged install byte-identical."""
    if not notes:
        return []
    shown = notes[:KNOWLEDGE_CAP]
    lines = ["## Knowledge routed to you", ""]
    # The topic renders QUOTED. This block lands in a seat's standing
    # instruction sheet, and a topic is data from a note's frontmatter - often
    # summarised from an outside source - so a topic phrased as an imperative
    # ("always CC the accountant") would otherwise read as an instruction line.
    # Quotes mark it as a label being reported, not an order being given; any
    # double quote inside the topic becomes a single quote so the label cannot
    # end its own quoting.
    lines += [f"- {n['id']} - \"{n['topic'].replace(chr(34), chr(39))}\" "
              f"(brain/knowledge/{n['file']})"
              for n in shown]
    extra = len(notes) - len(shown)
    if extra:
        lines.append(f"+ {extra} more in brain/knowledge/ tagged to you")
    lines += ["",
              "These are pointers, not content. The operator tagged them to this "
              "seat on purpose; open the ones that bear on the run you are doing, "
              "and do not assume the rest.",
              ""]
    return lines



def _strip_sentinel(text: str) -> str:
    return "\n".join(l for l in text.split("\n")
                     if not l.startswith(SENTINEL_PREFIX))


def _body_digest(text: str) -> str:
    return hashlib.sha256(_strip_sentinel(text).encode("utf-8")).hexdigest()


def _recorded_digest(text: str) -> str | None:
    for line in text.split("\n"):
        if line.startswith(SENTINEL_PREFIX):
            m = _HASH_RE.search(line)
            return m.group(1) if m else None
    return None


def _flat_yaml():
    """Load scripts/flat_yaml.py by explicit path rather than by import name, so
    this works the same whether or not scripts/ is on sys.path."""
    src = Path(__file__).resolve().parent / "flat_yaml.py"
    spec = importlib.util.spec_from_file_location("founderos_flat_yaml", src)
    if spec is None or spec.loader is None:  # pragma: no cover - packaging accident
        raise SystemExit("agents_sync: cannot load scripts/flat_yaml.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def load_registry(path: Path) -> list[dict]:
    if not path.exists():
        raise SystemExit(
            f"agents_sync: no registry at {path}. The org chart is the single "
            f"source for agent files; copy templates/roles/employees.yaml first.")
    try:
        rows = _flat_yaml().parse_flat_yaml(
            path.read_text(encoding="utf-8"), filename=str(path),
            record_key="employees")
    except ValueError as e:
        raise SystemExit(f"agents_sync: {e}") from None
    seen: set[str] = set()
    for i, r in enumerate(rows, 1):
        eid = r.get("id") or ""
        if not eid:
            raise SystemExit(f"agents_sync: registry entry #{i} has no id")
        if not ID_RE.match(eid):
            raise SystemExit(
                f"agents_sync: registry entry #{i} has invalid id '{eid}'. Ids are "
                f"lowercase letters, digits, and inner hyphens (max 64 chars) - they "
                f"become filenames under .claude/agents/ and nothing else is safe there.")
        if eid in seen:
            raise SystemExit(
                f"agents_sync: duplicate id '{eid}' (entry #{i}). Two rows with one id "
                f"would silently overwrite each other's agent file; merge or rename.")
        seen.add(eid)
    return rows


def _first_sentence(text: str, cap: int = 180) -> str:
    text = (text or "").strip()
    dot = text.find(". ")
    out = text[: dot + 1] if 0 < dot < cap else text[:cap]
    return out.strip()


def render_agent(row: dict, knowledge: list[dict] | None = None) -> str:
    """One agent file from one registry row. Everything here is READ from the
    row - nothing is invented, because this file is the seat's standing
    instruction sheet and an invented line would be a permission nobody granted.

    `knowledge` is the already-filtered pointer list for this seat (see
    _seat_knowledge). It is folded in HERE, inside the render, so the digest
    below covers it and the file-ownership rules need no new cases."""
    eid = row.get("id", "")
    title = (row.get("job_title") or eid).strip()
    desc = _first_sentence(row.get("job_description", ""))
    tools = (row.get("tools") or "").strip()
    head = [
        "---",
        f"name: {eid}",
        f"description: {title}. {desc}".rstrip(),
        f"tools: {tools}" if tools else "tools:",
        "---",
    ]
    body = [
        "",
        f"# {title}",
        "",
        f"You are the `{eid}` seat on this operator's org chart "
        f"(roles/employees.yaml). The row that generated this file IS your "
        f"contract: the operator manages you by editing it, and your job is to "
        f"stay inside it even when a wider action looks helpful.",
        "",
        "## The job",
        "",
        (row.get("job_description") or "").strip(),
        "",
        f"**The measure you are judged by:** {(row.get('kpi') or 'not set').strip()}",
        f"**Status:** {(row.get('status') or 'gated').strip()} - if gated, you run "
        f"only when the operator dispatches you, and your first real run is what "
        f"earns active.",
        "",
        "## Read these first",
        "",
        f"{(row.get('inputs') or 'nothing named - ask before reading widely').strip()}",
        "",
        "Also read `core/working-preferences.md` if it exists - its Active rows "
        "are how this operator wants to be worked with, and they gate your "
        "output the same way they gate every other surface.",
        "",
    ] + _knowledge_block(knowledge or []) + [
        "## What you may write",
        "",
        f"{(row.get('may_write') or 'nothing - this is a propose-only seat').strip()}",
        "",
        "## Never",
        "",
        f"{(row.get('never') or 'act outside the row above').strip()}",
        "",
        "The `never` field above is controlling. If it names no connector, "
        "nothing leaves this machine by your hand: no send, no post, no external "
        "call - drafts stop at files, and delivery belongs to the operator. If "
        "it explicitly names a connector, use only that connector, only for the "
        "action the row names, and only under the row's consent rule.",
        "",
        "## Your closing act (every run)",
        "",
        "Record the run so it leaves a trace whether or not anyone was watching:",
        "",
        "```",
        f"python scripts/agent_runs.py record --seat {eid} "
        f"--trigger \"<what set this run off>\" "
        f"--read \"<files actually read>\" "
        f"--produced \"<files or item ids written>\" --outcome ok",
        "```",
        "",
        "Use `--outcome refused --could-not \"<why>\"` when the charter said no, "
        "and `--outcome failed --could-not \"<why>\"` when it broke - the script "
        "requires the reason for both. A refusal is the charter working, not a "
        "failure. Skip silently if the script is absent.",
        "",
    ]
    digest = hashlib.sha256("\n".join(head + body).encode("utf-8")).hexdigest()
    sentinel = f"{SENTINEL_PREFIX} | body-sha256:{digest} -->"
    return "\n".join(head + [sentinel] + body)


def is_generated(path: Path) -> bool:
    try:
        return SENTINEL_PREFIX in path.read_text(encoding="utf-8")
    except OSError:
        return False


def _classify_owned(text: str, wanted_text: str | None) -> str:
    """For a file carrying the marker: is it still OURS to touch?

    Returns one of:
      clean    - matches its row's render exactly
      stale    - untouched generated content that no longer matches the row
      orphan   - untouched generated content whose row is retired or gone
      modified - the operator (or anyone) edited below the marker; NEVER touched
    """
    recorded = _recorded_digest(text)
    if recorded is not None:
        if recorded != _body_digest(text):
            return "modified"
        if wanted_text is None:
            return "orphan"
        return "clean" if text == wanted_text else "stale"
    # Legacy marker with no digest: owned only when the content (minus the
    # marker line) exactly matches the current render - then apply may rewrite
    # it to the digest form. Anything else could carry the operator's edits,
    # and a guess here destroys their work, so it is treated as modified.
    if wanted_text is not None and _strip_sentinel(text) == _strip_sentinel(wanted_text):
        return "stale"
    return "modified"


def compute(registry: Path, agents_dir: Path,
            knowledge_dir: Path | None = None) -> dict:
    """The full drift picture, computed once and shared by check and apply.

    knowledge_dir is read, never written. Passing it means the render reflects
    today's tags, so tagging a note is itself drift and apply is what converges
    it - the same loop editing a registry row already goes through."""
    rows = load_registry(registry)
    live = {r["id"] for r in rows if (r.get("status") or "") != "retired"}
    notes = _scan_knowledge(knowledge_dir)
    wanted = {r["id"]: render_agent(r, _seat_knowledge(r["id"], knowledge_dir, notes))
              for r in rows if (r.get("status") or "") != "retired"}
    # A tag naming no live row renders nothing and is never auto-cleaned: a
    # retired seat's notes stay tagged in case the seat comes back. Reported
    # like a bad wikilink - named, not fatal.
    dangling = sorted({seat for note in notes
                       for seat in note["seats"] if seat not in live})
    existing = {p.stem: p for p in sorted(agents_dir.glob("*.md"))} \
        if agents_dir.is_dir() else {}

    missing = [i for i in wanted if i not in existing]
    stale, foreign, orphan, modified = [], [], [], []
    for stem, p in existing.items():
        text = p.read_text(encoding="utf-8") if p.is_file() else ""
        mine = SENTINEL_PREFIX in text
        if stem in wanted:
            if not mine:
                foreign.append(stem)  # a hand-written file shadows the row - never touched
                continue
            kind = _classify_owned(text, wanted[stem])
            if kind == "stale":
                stale.append(stem)
            elif kind == "modified":
                modified.append(stem)
        elif mine:
            kind = _classify_owned(text, None)
            if kind == "orphan":
                orphan.append(stem)  # row retired or deleted; verified ours - may go
            else:
                modified.append(stem)  # edited or unverifiable - never deleted
        # not mine and not in wanted: someone else's agent - drift's job to name
    return {"wanted": wanted, "existing": existing, "missing": missing,
            "stale": stale, "foreign": foreign, "orphan": orphan,
            "modified": modified, "dangling": dangling}


def _safe_target(agents_dir: Path, stem: str) -> Path:
    """The one place a stem becomes a path. Refuses anything that would land
    outside the agents dir - the load-time id check should make this
    unreachable, but a write outside the boundary is the failure worth a
    second, mechanical lock."""
    target = (agents_dir / f"{stem}.md").resolve()
    if not target.is_relative_to(agents_dir.resolve()):
        raise SystemExit(f"agents_sync: refusing to touch {target} - outside "
                         f"{agents_dir}. A seat id must stay a bare filename.")
    return target


def cmd_check(args) -> int:
    state = compute(Path(args.registry), Path(args.agents_dir),
                    Path(args.knowledge_dir))
    drift = {k: state[k] for k in ("missing", "stale", "orphan", "foreign", "modified")}
    clean = not any(drift.values())
    if args.json:
        print(json.dumps({"clean": clean,
                          **{k: sorted(v) for k, v in drift.items()},
                          "dangling": sorted(state["dangling"])},
                         ensure_ascii=True))
        return 0 if clean else 1
    for i in state["missing"]:
        print(f"[missing] {i}: registry row has no agent file - run apply")
    for i in state["stale"]:
        print(f"[stale] {i}: agent file no longer matches its registry row - run apply")
    for i in state["orphan"]:
        print(f"[orphan] {i}: generated agent file with no live registry row - "
              f"apply removes it")
    for i in state["foreign"]:
        print(f"[foreign] {i}: hand-written agent file shadows a registry row - "
              f"left alone; fold it into the row or rename it")
    for i in state["modified"]:
        print(f"[modified] {i}: generated agent file was edited after generation - "
              f"left alone; fold the edit into the registry row, or delete the "
              f"file yourself and run apply")
    for i in state["dangling"]:
        print(f"[dangling-tag] {i}: knowledge notes are tagged to a seat with no "
              f"live registry row - nothing routed, nothing cleaned; the tag waits "
              f"in case the seat comes back")
    if clean:
        print(f"agents_sync: {len(state['wanted'])} seat(s), agent files match the "
              f"registry.")
        return 0
    return 1


def cmd_apply(args) -> int:
    agents_dir = Path(args.agents_dir)
    state = compute(Path(args.registry), agents_dir, Path(args.knowledge_dir))
    agents_dir.mkdir(parents=True, exist_ok=True)
    written, removed = [], []
    for i in state["missing"] + state["stale"]:
        _safe_target(agents_dir, i).write_text(state["wanted"][i],
                                               encoding="utf-8", newline="\n")
        written.append(i)
    for i in state["orphan"]:
        _safe_target(agents_dir, i).unlink()
        removed.append(i)
    for i in state["foreign"]:
        print(f"[foreign] {i}: hand-written file left alone")
    for i in state["modified"]:
        print(f"[modified] {i}: edited after generation - left alone; fold the "
              f"edit into the registry row, or delete the file and re-run apply")
    print(f"agents_sync: wrote {len(written)}, removed {len(removed)}, "
          f"{len(state['wanted'])} seat(s) total.")
    return 1 if state["modified"] else 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Generate .claude/agents/ from roles/employees.yaml. One source.")
    sub = p.add_subparsers(dest="cmd", required=True)
    for name, fn, help_text in (
            ("check", cmd_check, "Report drift between registry and agent files."),
            ("apply", cmd_apply, "Write agent files from the registry, remove orphans.")):
        sp = sub.add_parser(name, help=help_text)
        sp.add_argument("--registry", default=str(REGISTRY))
        sp.add_argument("--agents-dir", dest="agents_dir", default=str(AGENTS_DIR))
        sp.add_argument("--knowledge-dir", dest="knowledge_dir",
                        default=str(KNOWLEDGE_DIR))
        if name == "check":
            sp.add_argument("--json", action="store_true")
        sp.set_defaults(func=fn)
    args = p.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
