#!/usr/bin/env python3
"""Pre-commit / CI guard: scans content for private-name leaks, em/en dashes,
and AI-attribution trailers. One scanner, three front-ends so the local hooks
and CI cannot drift apart.

Modes:
    --staged              Scan `git diff --cached` added lines (L2 pre-commit hook).
    --message <path>      Scan a commit-message file (L2 commit-msg hook).
    --range <BASE..HEAD>  Scan every commit in a range (L3 CI). Exit 1 on any
                          violation so the check fails the build.

Check-sets:
    private-name  Regexes from scripts/private-name-patterns.txt (one per line;
                  # comments and blanks ignored). Operator-local and gitignored:
                  a contributor without the file (or with an empty one) gets NO
                  name check, only voice + attribution. Override the path with
                  PRIVATE_NAME_PATTERNS_FILE (CI loads it from the
                  *_PRIVATE_AUDIT_PATTERNS secret this way).
    emdash        Em-dash (U+2014) / en-dash (U+2013). Flagged in the commit
                  message AND in added product lines: this is a public product
                  repo whose house voice bans them. (The private OS scanner
                  exempts diff bodies because those carry captured transcripts;
                  a public product repo does not, so we scan them.) Escape
                  hatch: ALLOW_EMDASH=1.
    attribution   Co-Authored-By: Claude / Generated with Claude Code trailers.
                  Checked on every line, every mode. Line-start anchored so rule
                  documentation and regex literals do not self-trigger. NOT
                  bypassed by ALLOW_EMDASH.

Graceful no-op: the .githooks wrappers exit 0 when Python is absent, so this
never breaks a user's `git commit`. With Python present but no patterns file,
the name check is skipped (voice + attribution still run). Exit 1 on any
violation in every mode; exit 0 when clean.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

# Built via chr() (not the literal chars) so this scanner's own source stays
# ASCII and never trips the em-dash check when it is committed.
EM_DASH = chr(0x2014)
EN_DASH = chr(0x2013)

# Attribution patterns anchored to line start (after an optional unified-diff
# marker + / - and whitespace). Real git trailers begin at column 0; rule docs
# and regex source literals do not, so the anchoring removes the
# self-trigger-on-our-own-docs false-positive class.
ATTRIBUTION_PATTERNS = [
    re.compile(r"^[+\- ]?\s*Co-Authored-By:\s*Claude", re.IGNORECASE),
    re.compile(r"^[+\- ]?\s*Co-Authored-By:.*(?:claude|anthropic)", re.IGNORECASE),
    re.compile(r"^[+\- ]?\s*Generated with.*Claude Code", re.IGNORECASE),
    re.compile(r"^[+\- ]?\s*Generated by Claude", re.IGNORECASE),
    re.compile(r"^[+\- ]?\s*\U0001F916\s*Generated", re.IGNORECASE),
]


def _force_utf8_streams() -> None:
    """Make stdout/stderr UTF-8 tolerant so printing a flagged em-dash line on a
    Windows cp1252 console degrades to '?' instead of crashing (a crash would
    exit non-1 and could let a bad commit through)."""
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass


def load_patterns(patterns_file: Path) -> list[re.Pattern[str]]:
    if not patterns_file.exists():
        return []
    patterns = []
    for line in patterns_file.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            patterns.append(re.compile(line))
        except re.error:
            pass
    return patterns


# A long unbroken base64 run (embedded font/image data URIs). A short name regex
# like \bSam\b can match inside base64 because +, / and = are non-word chars, so
# \b boundaries fire. Skip these lines for every check-set.
_BASE64_RUN = re.compile(r"[A-Za-z0-9+/]{200,}={0,2}")


def is_base64_blob(line: str) -> bool:
    stripped = line.strip()
    if len(stripped) < 200:
        return False
    return _BASE64_RUN.search(stripped) is not None


def scan_text(
    text: str,
    patterns: list[re.Pattern[str]],
    *,
    allow_emdash: bool = False,
    check_dashes: bool = True,
) -> list[str]:
    """Scan text line by line for all three check-sets. Returns rendered
    offending lines tagged with the kind."""
    offending: list[str] = []
    for line_num, raw in enumerate(text.splitlines(), 1):
        if is_base64_blob(raw):
            continue
        line = raw.rstrip()
        for pat in patterns:
            if pat.search(raw):
                offending.append(f"  [private-name] line {line_num}: {line}")
                break
        if check_dashes and not allow_emdash and (EM_DASH in raw or EN_DASH in raw):
            offending.append(f"  [emdash] line {line_num}: {line}")
        for ap in ATTRIBUTION_PATTERNS:
            if ap.search(raw):
                offending.append(f"  [attribution] line {line_num}: {line}")
                break
    return offending


def get_staged_diff() -> str:
    result = subprocess.run(
        ["git", "diff", "--cached", "--no-color"],
        text=True,
        capture_output=True,
        encoding="utf-8",
        errors="replace",
    )
    if result.returncode != 0:
        print(
            f"git diff --cached failed (exit {result.returncode}): {result.stderr.strip()}",
            file=sys.stderr,
        )
        sys.exit(1)
    return result.stdout


def _added_lines(diff: str) -> str:
    return "\n".join(
        line[1:]
        for line in diff.splitlines()
        if line.startswith("+") and not line.startswith("+++")
    )


def resolve_patterns_file() -> Path:
    override = os.environ.get("PRIVATE_NAME_PATTERNS_FILE")
    if override:
        return Path(override)
    return Path(__file__).resolve().parent / "private-name-patterns.txt"


def _git_text(cmd: list[str], timeout: int = 15) -> str:
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=timeout,
        )
    except Exception:
        return ""
    return result.stdout if result.returncode == 0 else ""


def _rev_parse(ref: str) -> str:
    return _git_text(["git", "rev-parse", ref], timeout=10).strip()


def _commit_message(sha: str) -> str:
    return _git_text(["git", "log", "-1", "--format=%B", sha], timeout=10)


def _commit_diff(sha: str) -> str:
    return _git_text(["git", "show", "--format=", sha], timeout=15)


def _commits_in_range(rng: str) -> list[str]:
    """Resolve a range to commit SHAs. Accepts BASE..HEAD, a single ref, or a
    GitHub all-zeros BASE (new branch push), scanned as just the tip."""
    if ".." in rng:
        base, _, head = rng.partition("..")
        base = base.rstrip(".")
        head = head or "HEAD"
        if base and set(base) <= {"0"}:
            sha = _rev_parse(head)
            return [sha] if sha else []
        out = _git_text(["git", "log", "--format=%H", f"{base}..{head}"])
        return out.strip().splitlines() if out else []
    sha = _rev_parse(rng)
    return [sha] if sha else []


def _report(header: str, offending: list[str]) -> None:
    print(header, file=sys.stderr)
    for line in offending:
        print(line, file=sys.stderr)
    print("", file=sys.stderr)
    print(
        "Escape hatch: ALLOW_EMDASH=1 bypasses em/en dash (not private-name or attribution).",
        file=sys.stderr,
    )


def run_staged(patterns: list[re.Pattern[str]], allow_emdash: bool) -> int:
    diff = get_staged_diff()
    offending = scan_text(_added_lines(diff), patterns, allow_emdash=allow_emdash)
    if offending:
        _report("BLOCKED: guard violations in staged diff:", offending)
        return 1
    return 0


def run_message(path: str, patterns: list[re.Pattern[str]], allow_emdash: bool) -> int:
    try:
        text = Path(path).read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        print(f"Could not read commit message at {path}: {exc}", file=sys.stderr)
        return 1
    offending = scan_text(text, patterns, allow_emdash=allow_emdash)
    if offending:
        _report("BLOCKED: guard violations in commit message:", offending)
        return 1
    return 0


def run_range(rng: str, patterns: list[re.Pattern[str]], allow_emdash: bool) -> int:
    shas = _commits_in_range(rng)
    if not shas:
        return 0
    total = 0
    for sha in shas:
        offending = scan_text(_commit_message(sha), patterns, allow_emdash=allow_emdash)
        offending += scan_text(_added_lines(_commit_diff(sha)), patterns, allow_emdash=allow_emdash)
        if offending:
            print(f"BLOCKED: guard violations in commit {sha[:8]}:", file=sys.stderr)
            for line in offending:
                print(line, file=sys.stderr)
            total += len(offending)
    if total:
        print("", file=sys.stderr)
        print(
            f"guard: {total} violation(s). Escape hatch (em/en dash only): ALLOW_EMDASH=1.",
            file=sys.stderr,
        )
        return 1
    return 0


def main() -> int:
    _force_utf8_streams()
    args = sys.argv[1:]
    usage = "Usage: check-private-names.py --staged | --message <path> | --range <BASE..HEAD>"
    if not args:
        print(usage, file=sys.stderr)
        return 1

    patterns_file = resolve_patterns_file()
    patterns = load_patterns(patterns_file)
    if not patterns and patterns_file.exists():
        print(
            f"WARNING: private-name guard is installed ({patterns_file}) but defines no "
            "patterns. Name check INACTIVE (em-dash + attribution still enforced). "
            "Add names to activate it.",
            file=sys.stderr,
        )

    allow_emdash = os.environ.get("ALLOW_EMDASH", "0") == "1"

    if args[0] == "--staged":
        return run_staged(patterns, allow_emdash)
    if args[0] == "--message" and len(args) >= 2:
        return run_message(args[1], patterns, allow_emdash)
    if args[0] == "--range" and len(args) >= 2:
        return run_range(args[1], patterns, allow_emdash)

    print(usage, file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
