#!/usr/bin/env python3
"""Pre-commit / CI guard: scans content for private-name leaks, em/en dashes,
and AI-attribution trailers. One scanner, three front-ends so the local hooks
and CI cannot drift apart.

Modes:
    --staged              Scan `git diff --cached` added lines (L2 pre-commit hook).
    --message <path>      Scan a commit-message file (L2 commit-msg hook).
    --range <BASE..HEAD>  Scan every commit in a range (L3 CI). Exit 1 on any
                          violation so the check fails the build.

Check-sets:
    private-name  Regexes from scripts/private-name-patterns.txt (one per line;
                  # comments and blanks ignored). Operator-local and gitignored:
                  a contributor without the file (or with an empty one) gets NO
                  name check, only voice + attribution. Override the path with
                  PRIVATE_NAME_PATTERNS_FILE (CI loads it from the
                  *_PRIVATE_AUDIT_PATTERNS secret this way).
    emdash        Em-dash (U+2014) / en-dash (U+2013). Flagged in the commit
                  message AND in added product lines: this is a public product
                  repo whose house voice bans them. (The private OS scanner
                  exempts diff bodies because those carry captured transcripts;
                  a public product repo does not, so we scan them.) Escape
                  hatch: ALLOW_EMDASH=1.
    attribution   Co-Authored-By: Claude / Generated with Claude Code trailers.
                  Checked on every line, every mode. Line-start anchored so rule
                  documentation and regex literals do not self-trigger. NOT
                  bypassed by ALLOW_EMDASH.
    secret        Token-shaped strings (Telegram bot token, sk-/sk-ant- keys,
                  Slack/GitHub/AWS/Google/Stripe tokens, PEM private-key headers)
                  and API-KEY / TOKEN / SECRET / PASSWORD style assignments set to
                  a high-entropy value. Always on, not gated on the patterns file,
                  NOT bypassed by ALLOW_EMDASH. The matched value is never echoed.
                  This is the out-of-the-box half of the guard: even with an empty
                  patterns file a stray secret in a tracked file is blocked.
    remote-safety (--staged only) Refuses to commit while the founder's personal
                  data is tracked (core/identity.md is in the index) AND any git
                  remote's push destination still points at the public FounderOS
                  repo (github.com/ARCASSystems). In that state one `git push`
                  publishes their identity. Setup and own-your-history rename the
                  public remote to founderos-upstream and disable its push URL;
                  this check is the backstop for installs that missed that step.
                  Passes silently in the public dev repo (identity is not tracked
                  there), on CI (--range never runs it), and after the rename.

Graceful no-op: the .githooks wrappers exit 0 when Python is absent, so this
never breaks a user's `git commit`. With Python present but no patterns file,
only the name check is skipped (secret + em-dash + attribution still run, so the
guard does useful work out of the box). Exit 1 on any violation in every mode;
exit 0 when clean.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

# Built via chr() (not the literal chars) so this scanner's own source stays
# ASCII and never trips the em-dash check when it is committed.
EM_DASH = chr(0x2014)
EN_DASH = chr(0x2013)

# Attribution patterns anchored to line start (after an optional unified-diff
# marker + / - and whitespace). Real git trailers begin at column 0; rule docs
# and regex source literals do not, so the anchoring removes the
# self-trigger-on-our-own-docs false-positive class.
ATTRIBUTION_PATTERNS = [
    re.compile(r"^[+\- ]?\s*Co-Authored-By:\s*Claude", re.IGNORECASE),
    re.compile(r"^[+\- ]?\s*Co-Authored-By:.*(?:claude|anthropic)", re.IGNORECASE),
    re.compile(r"^[+\- ]?\s*Generated with.*Claude Code", re.IGNORECASE),
    re.compile(r"^[+\- ]?\s*Generated by Claude", re.IGNORECASE),
    re.compile(r"^[+\- ]?\s*\U0001F916\s*Generated", re.IGNORECASE),
]


def _force_utf8_streams() -> None:
    """Make stdout/stderr UTF-8 tolerant so printing a flagged em-dash line on a
    Windows cp1252 console degrades to '?' instead of crashing (a crash would
    exit non-1 and could let a bad commit through)."""
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass


def load_patterns(patterns_file: Path) -> list[re.Pattern[str]]:
    if not patterns_file.exists():
        return []
    patterns = []
    for line in patterns_file.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            patterns.append(re.compile(line))
        except re.error:
            pass
    return patterns


# A long unbroken base64 run (embedded font/image data URIs). A short name regex
# like \bSam\b can match inside base64 because +, / and = are non-word chars, so
# \b boundaries fire. Skip these lines for every check-set.
_BASE64_RUN = re.compile(r"[A-Za-z0-9+/]{200,}={0,2}")


def is_base64_blob(line: str) -> bool:
    stripped = line.strip()
    if len(stripped) < 200:
        return False
    return _BASE64_RUN.search(stripped) is not None


# --- Secret detection (always on; not gated on the patterns file, not bypassable
# by ALLOW_EMDASH). A secret in a tracked file is the failure the privacy work
# exists to prevent, so the check ships active out of the box. Patterns are
# written so this scanner's own regex source cannot self-trigger (no literal here
# forms a complete secret of its own shape).
SECRET_SHAPE_PATTERNS = [
    # Telegram BotFather token: <8-10 digits>:<35+ url-safe chars>.
    ("telegram-bot-token", re.compile(r"\b\d{8,10}:[A-Za-z0-9_-]{35,}")),
    # Anthropic / OpenAI keys. The ant-/proj- markers are rare literals, so a
    # hyphenated body is safe; plain sk- needs 40 contiguous alnum so hyphenated
    # slugs (sk-related-thing) cannot false-trip.
    ("anthropic-key", re.compile(r"\bsk-ant-[A-Za-z0-9_-]{20,}")),
    ("openai-proj-key", re.compile(r"\bsk-proj-[A-Za-z0-9_-]{20,}")),
    ("openai-key", re.compile(r"\bsk-[A-Za-z0-9]{40,}\b")),
    # Slack tokens (xoxb-, xoxp-, xoxa-, xoxr-, xoxs-).
    ("slack-token", re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{10,}\b")),
    # GitHub tokens.
    ("github-token", re.compile(r"\b(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{36,}\b")),
    ("github-pat", re.compile(r"\bgithub_pat_[A-Za-z0-9_]{40,}\b")),
    # AWS access key id.
    ("aws-access-key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    # Google API key.
    ("google-api-key", re.compile(r"\bAIza[0-9A-Za-z_-]{35}\b")),
    # Stripe live / test keys.
    ("stripe-key", re.compile(r"\b[rs]k_(?:live|test)_[A-Za-z0-9]{16,}\b")),
    # PEM private key header.
    ("private-key-block", re.compile(r"-----BEGIN (?:RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY-----")),
]

# Secret-NAMED assignment: an API-KEY / TOKEN / SECRET / PASSWORD style name set
# to a long, high-entropy value. The value is validated (not a placeholder, mixed
# letters and digits) so docs and example lines do not false-trip.
_SECRET_NAME = re.compile(
    r"(?i)\b[a-z0-9_]*(?:api[_-]?key|secret[_-]?key|access[_-]?key|access[_-]?token"
    r"|auth[_-]?token|bot[_-]?token|api[_-]?token|client[_-]?secret|private[_-]?key"
    r"|secret|passwd|password)\b\s*[:=]\s*"
)
_SECRET_VALUE = re.compile(r"['\"]?([^\s'\"#,;]{16,})")
_PLACEHOLDER = re.compile(
    r"(?i)(your|example|placeholder|change[_-]?me|xxx|<[^>]*>|\.\.\.|todo|redact"
    r"|fill|here|none|null|true|false|enabled|disabled|sample|dummy"
    r"|\$\{|\$\(|%[a-z_]+%)"
)


def _looks_like_real_secret(value: str) -> bool:
    """A captured assignment value is a likely real secret only when it mixes
    letters and digits (high entropy) and is not an obvious placeholder. The 16+
    length floor is already enforced by the value regex. Requiring both letters
    and digits keeps prose, paths, and bare URLs from false-tripping."""
    if _PLACEHOLDER.search(value):
        return False
    has_alpha = any(c.isalpha() for c in value)
    has_digit = any(c.isdigit() for c in value)
    return has_alpha and has_digit


def find_secret(line: str) -> str | None:
    """Return a short kind-label if the line carries a likely secret, else None."""
    for kind, pat in SECRET_SHAPE_PATTERNS:
        if pat.search(line):
            return kind
    m = _SECRET_NAME.search(line)
    if m:
        tail = line[m.end():]
        v = _SECRET_VALUE.match(tail)
        if v and _looks_like_real_secret(v.group(1)):
            return "named-secret-assignment"
    return None


def scan_text(
    text: str,
    patterns: list[re.Pattern[str]],
    *,
    allow_emdash: bool = False,
    check_dashes: bool = True,
    check_secrets: bool = True,
) -> list[str]:
    """Scan text line by line for all four check-sets. Returns rendered offending
    lines tagged with the kind. Secret values are never echoed back."""
    offending: list[str] = []
    for line_num, raw in enumerate(text.splitlines(), 1):
        if is_base64_blob(raw):
            continue
        line = raw.rstrip()
        for pat in patterns:
            if pat.search(raw):
                offending.append(f"  [private-name] line {line_num}: {line}")
                break
        if check_dashes and not allow_emdash and (EM_DASH in raw or EN_DASH in raw):
            offending.append(f"  [emdash] line {line_num}: {line}")
        for ap in ATTRIBUTION_PATTERNS:
            if ap.search(raw):
                offending.append(f"  [attribution] line {line_num}: {line}")
                break
        if check_secrets:
            kind = find_secret(raw)
            if kind:
                offending.append(
                    f"  [secret:{kind}] line {line_num}: possible secret detected (value hidden)"
                )
    return offending


def get_staged_diff() -> str:
    result = subprocess.run(
        ["git", "diff", "--cached", "--no-color"],
        text=True,
        capture_output=True,
        encoding="utf-8",
        errors="replace",
    )
    if result.returncode != 0:
        print(
            f"git diff --cached failed (exit {result.returncode}): {result.stderr.strip()}",
            file=sys.stderr,
        )
        sys.exit(1)
    return result.stdout


def _added_lines(diff: str) -> str:
    return "\n".join(
        line[1:]
        for line in diff.splitlines()
        if line.startswith("+") and not line.startswith("+++")
    )


def resolve_patterns_file() -> Path:
    override = os.environ.get("PRIVATE_NAME_PATTERNS_FILE")
    if override:
        return Path(override)
    return Path(__file__).resolve().parent / "private-name-patterns.txt"


def _git_text(cmd: list[str], timeout: int = 15) -> str:
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=timeout,
        )
    except Exception:
        return ""
    return result.stdout if result.returncode == 0 else ""


def _rev_parse(ref: str) -> str:
    return _git_text(["git", "rev-parse", ref], timeout=10).strip()


def _commit_message(sha: str) -> str:
    return _git_text(["git", "log", "-1", "--format=%B", sha], timeout=10)


def _commit_diff(sha: str) -> str:
    return _git_text(["git", "show", "--format=", sha], timeout=15)


def _commits_in_range(rng: str) -> list[str]:
    """Resolve a range to commit SHAs. Accepts BASE..HEAD, a single ref, or a
    GitHub all-zeros BASE (new branch push), scanned as just the tip."""
    if ".." in rng:
        base, _, head = rng.partition("..")
        base = base.rstrip(".")
        head = head or "HEAD"
        if base and set(base) <= {"0"}:
            sha = _rev_parse(head)
            return [sha] if sha else []
        out = _git_text(["git", "log", "--format=%H", f"{base}..{head}"])
        return out.strip().splitlines() if out else []
    sha = _rev_parse(rng)
    return [sha] if sha else []


def _report(header: str, offending: list[str]) -> None:
    print(header, file=sys.stderr)
    for line in offending:
        print(line, file=sys.stderr)
    print("", file=sys.stderr)
    print(
        "Escape hatch: ALLOW_EMDASH=1 bypasses em/en dash (not private-name, attribution, secret, or remote-safety).",
        file=sys.stderr,
    )


# Matches a push destination at the public FounderOS repo, https or ssh form.
_PUBLIC_REPO_URL = re.compile(r"github\.com[:/]ARCASSystems/", re.IGNORECASE)


def check_remote_safety() -> list[str]:
    """Return violations when personal data is tracked and a remote can still
    push to the public repo. See the remote-safety check-set in the module
    docstring. Any git error (not a repo, no remotes, no config matches) is a
    silent pass - this backstop must never break an ordinary commit."""
    if not _git_text(["git", "ls-files", "--", "core/identity.md"], timeout=10).strip():
        return []
    config = _git_text(["git", "config", "--get-regexp", r"^remote\."], timeout=10)
    if not config:
        return []
    remotes: dict[str, dict[str, str]] = {}
    for line in config.splitlines():
        key, _, value = line.partition(" ")
        parts = key.split(".")
        if len(parts) < 3 or parts[-1] not in ("url", "pushurl"):
            continue
        name = ".".join(parts[1:-1])
        remotes.setdefault(name, {})[parts[-1]] = value.strip()
    offending: list[str] = []
    for name, urls in sorted(remotes.items()):
        push_target = urls.get("pushurl") or urls.get("url", "")
        if _PUBLIC_REPO_URL.search(push_target):
            offending.append(
                f"  [remote-safety] remote '{name}' can push to the public FounderOS repo\n"
                f"    while your personal data (core/identity.md) is tracked. One git push\n"
                f"    would publish it. Fix (keeps updates flowing in, blocks anything out):\n"
                f"      git remote rename {name} founderos-upstream\n"
                f"      git remote set-url --push founderos-upstream DISABLED\n"
                f"    Or say 'own my history' and the OS does it for you."
            )
    return offending


def run_staged(patterns: list[re.Pattern[str]], allow_emdash: bool) -> int:
    offending = check_remote_safety()
    diff = get_staged_diff()
    offending += scan_text(_added_lines(diff), patterns, allow_emdash=allow_emdash)
    if offending:
        _report("BLOCKED: guard violations in staged diff:", offending)
        return 1
    return 0


def run_message(path: str, patterns: list[re.Pattern[str]], allow_emdash: bool) -> int:
    try:
        text = Path(path).read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        print(f"Could not read commit message at {path}: {exc}", file=sys.stderr)
        return 1
    offending = scan_text(text, patterns, allow_emdash=allow_emdash)
    if offending:
        _report("BLOCKED: guard violations in commit message:", offending)
        return 1
    return 0


def run_range(rng: str, patterns: list[re.Pattern[str]], allow_emdash: bool) -> int:
    shas = _commits_in_range(rng)
    if not shas:
        return 0
    total = 0
    for sha in shas:
        offending = scan_text(_commit_message(sha), patterns, allow_emdash=allow_emdash)
        offending += scan_text(_added_lines(_commit_diff(sha)), patterns, allow_emdash=allow_emdash)
        if offending:
            print(f"BLOCKED: guard violations in commit {sha[:8]}:", file=sys.stderr)
            for line in offending:
                print(line, file=sys.stderr)
            total += len(offending)
    if total:
        print("", file=sys.stderr)
        print(
            f"guard: {total} violation(s). Escape hatch (em/en dash only): ALLOW_EMDASH=1.",
            file=sys.stderr,
        )
        return 1
    return 0


def main() -> int:
    _force_utf8_streams()
    args = sys.argv[1:]
    usage = "Usage: check-private-names.py --staged | --message <path> | --range <BASE..HEAD>"
    if not args:
        print(usage, file=sys.stderr)
        return 1

    patterns_file = resolve_patterns_file()
    patterns = load_patterns(patterns_file)
    if not patterns and patterns_file.exists():
        print(
            f"WARNING: private-name guard is installed ({patterns_file}) but defines no "
            "patterns. Name check INACTIVE (secret, em-dash, and attribution checks still "
            "enforced). Add names to activate the name check too.",
            file=sys.stderr,
        )

    allow_emdash = os.environ.get("ALLOW_EMDASH", "0") == "1"

    if args[0] == "--staged":
        return run_staged(patterns, allow_emdash)
    if args[0] == "--message" and len(args) >= 2:
        return run_message(args[1], patterns, allow_emdash)
    if args[0] == "--range" and len(args) >= 2:
        return run_range(args[1], patterns, allow_emdash)

    print(usage, file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
